project:
  type: website

website:
  title: "Niagahoster - VIX Talent Database"
  navbar:
    background: primary
    left:
      - text: Dashboard
        menu: 
          - href: seo.qmd
            text: Niagahoster - SEO Outreach
          - href: uiux.qmd
            text: Niagahoster - UI/UX Designer

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

